### ISSUE TITLE
value coding-compliant  Error

### ISSUE THREAD

**Issue by dimohamdy** [qiscus/qiscus-chat-sdk-ios-sample#2]
I get a lot of this Errors that key in user defined attribute
 

> Failed to set (cornerRadiuss) user defined inspected property on (UIImageView): [<UIImageView 0x7fcc174310f0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key cornerRadiuss.
> 
>  [<UITextView 0x7fcc11075000> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key leftBorderWidth

If this values effect the Define please provide us with it

**Comment by ariefnurputranto** [comment]
hi @dimohamdy, if you got crash in cornerRadiuss and leftBorderWidth , you can remove cornerRadiuss & leftBorderWidth from .xib and change with programmatically

bdw, how to repro this crash? we need more info for this improvement.


Thanks

**Comment by dimohamdy** [comment]
it's only warning.
