### ISSUE TITLE
The Chat List does not not support loading more than 100 rooms yet

### ISSUE THREAD

**Issue by fahimj** [qiscus/qiscus-chat-sdk-ios-sample#4]
If a user has more than 100 rooms, the chat list only shows the first 100 chat rooms and does not support pagination yet.

**Comment by ariefnurputranto** [comment]
hi @fahimj, if you want to make over 100 chat rooms, you can create pagination when call api getAllChatRooms().

This func in UIChatListPresenter()

```
QiscusCore.shared.getAllChatRooms(showParticipant: true, showRemoved: false, showEmpty: true, page: page, limit: 100, onSuccess: { (results, meta) in
           //success
        }, onError: { (error) in
          //error
        })
```

Thanks
