### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by dimohamdy** [qiscus/qiscus-chat-sdk-ios-sample#5]
I get this crash 
Fatal error: You need to set App ID: file /Users/qiscus/iOS/SDK/QiscusCore/QiscusCore/QiscusCore.swift, line 422

**Comment by ariefnurputranto** [comment]
hi @dimohamdy , please move QiscusCore.setup(AppID: APP_ID) in appDelegate

for example you can check this : 
https://github.com/qiscus/qiscus-chat-sdk-ios-sample/blob/50e444d51789aada944645e50abb54e29daca610/Example/AppDelegate.swift#L25

Thanks

**Comment by dimohamdy** [comment]
Thanks
