### ISSUE TITLE
I couldn't run the sample app

### ISSUE THREAD

**Issue by azam3d** [qiscus/qiscus-chat-sdk-ios-sample#6]
It has error in UIChatPresenter.swift, line 132:
QiscusCore.shared.getPreviousMessagesById(roomID: roomId,limit: 10, messageId: **lastComment.id**, onSuccess:

Cannot convert value of type 'String' to expected argument type 'Int'

Please advice. Thanks.

**Comment by ariefnurputranto** [comment]
hi @azam3d , please using latest QiscusCore.

we change from int to String in latest QiscusCore
